import type { NextPage } from 'next'
import Head from 'next/head'
import client from '../apollo-client'
import Content from '@modules/common/Content'
import { AllUsersDocument, User } from '@generated/graphql'

interface Props {
  users: User[];
}

const Home: NextPage<Props>= ({ users }) => {
  console.log(users);
  return (
    <div>
      <Head>
        <title>Next.js Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content />
    </div>
  )
}

export async function getStaticProps() {
  try {
    const { data } = await client.query({
      query: AllUsersDocument
    });

    return {
      props: {
        users: data.users as User[]
      }
    }
  } catch (error) {
    console.log(error);
    return {
      props: {
        users: []
      }
    }
  }
}

export default Home;
